config/routes.rb
Loukhewtay::Application.routes.draw do
  get "authentification/sign_in"

  get "authentification/sign_out"

  get "accueil/index"

  resources :categorie_events

  resources :evenements

  resources :categorie_endroits

  resources :endroits

  resources :users

  root :to => 'authentification#sign_in'
  match 'authentification/sign_in'
  match '/index', :to=>'accueil#index'

end

app/models/categorie_endroit.rb
class CategorieEndroit < ActiveRecord::Base
  has_many :endroits
end

app/controllers/categorie_endroits_controller.rb
class CategorieEndroitsController < ApplicationController
  # GET /categorie_endroits
  # GET /categorie_endroits.json
  def index
    @categorie_endroits = CategorieEndroit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorie_endroits }
    end
  end

  # GET /categorie_endroits/1
  # GET /categorie_endroits/1.json
  def show
    @categorie_endroit = CategorieEndroit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorie_endroit }
    end
  end

  # GET /categorie_endroits/new
  # GET /categorie_endroits/new.json
  def new
    @categorie_endroit = CategorieEndroit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorie_endroit }
    end
  end

  # GET /categorie_endroits/1/edit
  def edit
    @categorie_endroit = CategorieEndroit.find(params[:id])
  end

  # POST /categorie_endroits
  # POST /categorie_endroits.json
  def create
    @categorie_endroit = CategorieEndroit.new(params[:categorie_endroit])

    respond_to do |format|
      if @categorie_endroit.save
        format.html { redirect_to @categorie_endroit, notice: 'Categorie endroit was successfully created.' }
        format.json { render json: @categorie_endroit, status: :created, location: @categorie_endroit }
      else
        format.html { render action: "new" }
        format.json { render json: @categorie_endroit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorie_endroits/1
  # PUT /categorie_endroits/1.json
  def update
    @categorie_endroit = CategorieEndroit.find(params[:id])

    respond_to do |format|
      if @categorie_endroit.update_attributes(params[:categorie_endroit])
        format.html { redirect_to @categorie_endroit, notice: 'Categorie endroit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorie_endroit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorie_endroits/1
  # DELETE /categorie_endroits/1.json
  def destroy
    @categorie_endroit = CategorieEndroit.find(params[:id])
    @categorie_endroit.destroy

    respond_to do |format|
      format.html { redirect_to categorie_endroits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categorie_endroits_helper.rb
module CategorieEndroitsHelper
end

app/views/categorie_endroits/_form.html.erb
<%= form_for(@categorie_endroit) do |f| %>
  <% if @categorie_endroit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorie_endroit.errors.count, "error") %> prohibited this categorie_endroit from being saved:</h2>

      <ul>
      <% @categorie_endroit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libelle %><br />
    <%= f.text_field :libelle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorie_endroits/edit.html.erb
<h1>Editing categorie_endroit</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorie_endroit %> |
<%= link_to 'Back', categorie_endroits_path %>

app/views/categorie_endroits/index.html.erb
<h1>Listing categorie_endroits</h1>

<table>
  <tr>
    <th>Libelle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorie_endroits.each do |categorie_endroit| %>
  <tr>
    <td><%= categorie_endroit.libelle %></td>
    <td><%= link_to 'Show', categorie_endroit %></td>
    <td><%= link_to 'Edit', edit_categorie_endroit_path(categorie_endroit) %></td>
    <td><%= link_to 'Destroy', categorie_endroit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categorie endroit', new_categorie_endroit_path %>

app/views/categorie_endroits/new.html.erb
<h1>New categorie_endroit</h1>

<%= render 'form' %>

<%= link_to 'Back', categorie_endroits_path %>

app/views/categorie_endroits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Libelle:</b>
  <%= @categorie_endroit.libelle %>
</p>


<%= link_to 'Edit', edit_categorie_endroit_path(@categorie_endroit) %> |
<%= link_to 'Back', categorie_endroits_path %>