config/routes.rb
Loukhewtay::Application.routes.draw do
  get "authentification/sign_in"

  get "authentification/sign_out"

  get "accueil/index"

  resources :categorie_events

  resources :evenements

  resources :categorie_endroits

  resources :endroits

  resources :users

  root :to => 'authentification#sign_in'
  match 'authentification/sign_in'
  match '/index', :to=>'accueil#index'

end

app/models/evenement.rb
class Evenement < ActiveRecord::Base
  belongs_to :user
  belongs_to :categorie_event
  belongs_to :endroit
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  # GET /evenements
  # GET /evenements.json
  def index
    @evenements = Evenement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @evenements }
    end
  end

  # GET /evenements/1
  # GET /evenements/1.json
  def show
    @evenement = Evenement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evenement }
    end
  end

  # GET /evenements/new
  # GET /evenements/new.json
  def new
    @evenement = Evenement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evenement }
    end
  end

  # GET /evenements/1/edit
  def edit
    @evenement = Evenement.find(params[:id])
  end

  # POST /evenements
  # POST /evenements.json
  def create
    @evenement = Evenement.new(params[:evenement])

    respond_to do |format|
      if @evenement.save
        format.html { redirect_to @evenement, notice: 'Evenement was successfully created.' }
        format.json { render json: @evenement, status: :created, location: @evenement }
      else
        format.html { render action: "new" }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /evenements/1
  # PUT /evenements/1.json
  def update
    @evenement = Evenement.find(params[:id])

    respond_to do |format|
      if @evenement.update_attributes(params[:evenement])
        format.html { redirect_to @evenement, notice: 'Evenement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evenements/1
  # DELETE /evenements/1.json
  def destroy
    @evenement = Evenement.find(params[:id])
    @evenement.destroy

    respond_to do |format|
      format.html { redirect_to evenements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/views/evenements/_form.html.erb
<%= form_for(@evenement) do |f| %>
  <% if @evenement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evenement.errors.count, "error") %> prohibited this evenement from being saved:</h2>

      <ul>
      <% @evenement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>5 %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :frequence %><br />
    <%= f.text_field :frequence %>
  </div>
  <div class="field">
    <%= f.label :confidentialite %><br />
    <%= f.text_field :confidentialite %>
  </div>
  <div class="field">
    <%= f.label :endroit_id %><br />
    <%= f.collection_select(:endroit_id, Endroit.all, :id, :nom) %>
  </div>
  <div class="field">
    <%= f.label :categorie_Event %><br />
    <%= f.collection_select(:categorieEvent_id, CategorieEvent.all, :id, :libelle) %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value=>session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<h1>Editing evenement</h1>

<%= render 'form' %>

<%= link_to 'Show', @evenement %> |
<%= link_to 'Back', evenements_path %>

app/views/evenements/index.html.erb
<h1>Listing evenements</h1>

<% @evenements.each do |evenement| %>
      <% if evenement.user.idfacebook
           @id = evenement.user.idfacebook
           url = "https://graph.facebook.com/"+@id.to_s+"/picture"
         else
           url = "/images/profile.jpg"
         end

      %>

      <div id="evenement">
        <div class="user"><img src= <%= url %> ><br/><b><%= evenement.user.login %></b></div>
        <div class="infoEvent">
          <span class="nomEvent"><%= evenement.nom %></span><br/>
          <span class="dateEvent"><%= evenement.date.to_date.to_formatted_s(:rfc822) %></span> &nbsp; | &nbsp;Au <span class="endroitEvent"><%= evenement.endroit.nom %></span><br/>
          <span class="descEvent"><%= evenement.description %></span><br/>
        </div>
        <div class="imageEvent"></div>
      </div>

<% end %>

<br />

<%= link_to 'New Evenement', new_evenement_path %>

app/views/evenements/new.html.erb
<h1>New evenement</h1>

<%= render 'form' %>

<%= link_to 'Back', evenements_path %>

app/views/evenements/show.html.erb
<p id="notice"><%= notice %></p>
<% if @evenement.user.idfacebook
     @id = @evenement.user.idfacebook
     url = "https://graph.facebook.com/"+@id.to_s+"/picture"
   else
     url = "/images/profile.jpg"
   end

%>

<div id="evenement">
  <div class="user"><img src= <%= url %> ><br/><b><%= @evenement.user.login %></b></div>
  <div class="infoEvent">
    <span class="nomEvent"><%= @evenement.nom %></span><br/>
    <span class="dateEvent"><%= @evenement.date.to_date.to_formatted_s(:rfc822) %></span> &nbsp; | &nbsp;Au <span class="endroitEvent"><%= @evenement.endroit.nom %></span><br/>
    <span class="descEvent"><%= @evenement.description %></span><br/>
  </div>
  <div class="imageEvent"></div>
</div>

<p>
  <b>Frequence:</b>
  <%= @evenement.frequence %>
</p>

<p>
  <b>Confidentialite:</b>
  <%= @evenement.confidentialite %>
</p>
<p>
  <b>Categorieevent:</b>
  <%#= @evenement.categorie_event.libelle %>
</p>

<p>
  <b>User:</b>

</p>


<%= link_to 'Edit', edit_evenement_path(@evenement) %> |
<%= link_to 'Back', evenements_path %>