config/routes.rb
Loukhewtay::Application.routes.draw do
  get "authentification/sign_in"

  get "authentification/sign_out"

  get "accueil/index"

  resources :categorie_events

  resources :evenements

  resources :categorie_endroits

  resources :endroits

  resources :users

  root :to => 'authentification#sign_in'
  match 'authentification/sign_in'
  match '/index', :to=>'accueil#index'

end

app/models/categorie_event.rb
class CategorieEvent < ActiveRecord::Base
  has_many :evenements
end

app/controllers/categorie_events_controller.rb
class CategorieEventsController < ApplicationController
  # GET /categorie_events
  # GET /categorie_events.json
  def index
    @categorie_events = CategorieEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorie_events }
    end
  end

  # GET /categorie_events/1
  # GET /categorie_events/1.json
  def show
    @categorie_event = CategorieEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorie_event }
    end
  end

  # GET /categorie_events/new
  # GET /categorie_events/new.json
  def new
    @categorie_event = CategorieEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorie_event }
    end
  end

  # GET /categorie_events/1/edit
  def edit
    @categorie_event = CategorieEvent.find(params[:id])
  end

  # POST /categorie_events
  # POST /categorie_events.json
  def create
    @categorie_event = CategorieEvent.new(params[:categorie_event])

    respond_to do |format|
      if @categorie_event.save
        format.html { redirect_to @categorie_event, notice: 'Categorie event was successfully created.' }
        format.json { render json: @categorie_event, status: :created, location: @categorie_event }
      else
        format.html { render action: "new" }
        format.json { render json: @categorie_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorie_events/1
  # PUT /categorie_events/1.json
  def update
    @categorie_event = CategorieEvent.find(params[:id])

    respond_to do |format|
      if @categorie_event.update_attributes(params[:categorie_event])
        format.html { redirect_to @categorie_event, notice: 'Categorie event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorie_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorie_events/1
  # DELETE /categorie_events/1.json
  def destroy
    @categorie_event = CategorieEvent.find(params[:id])
    @categorie_event.destroy

    respond_to do |format|
      format.html { redirect_to categorie_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categorie_events_helper.rb
module CategorieEventsHelper
end

app/views/categorie_events/_form.html.erb
<%= form_for(@categorie_event) do |f| %>
  <% if @categorie_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorie_event.errors.count, "error") %> prohibited this categorie_event from being saved:</h2>

      <ul>
      <% @categorie_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libelle %><br />
    <%= f.text_field :libelle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorie_events/edit.html.erb
<h1>Editing categorie_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorie_event %> |
<%= link_to 'Back', categorie_events_path %>

app/views/categorie_events/index.html.erb
<h1>Listing categorie_events</h1>

<table>
  <tr>
    <th>Libelle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorie_events.each do |categorie_event| %>
  <tr>
    <td><%= categorie_event.libelle %></td>
    <td><%= link_to 'Show', categorie_event %></td>
    <td><%= link_to 'Edit', edit_categorie_event_path(categorie_event) %></td>
    <td><%= link_to 'Destroy', categorie_event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categorie event', new_categorie_event_path %>

app/views/categorie_events/new.html.erb
<h1>New categorie_event</h1>

<%= render 'form' %>

<%= link_to 'Back', categorie_events_path %>

app/views/categorie_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Libelle:</b>
  <%= @categorie_event.libelle %>
</p>


<%= link_to 'Edit', edit_categorie_event_path(@categorie_event) %> |
<%= link_to 'Back', categorie_events_path %>